---
-- #%L
-- Orne Querydsl Utils
-- %%
-- Copyright (C) 2021 - 2022 Orne Developments
-- %%
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU Lesser General Public License as
-- published by the Free Software Foundation, either version 3 of the
-- License, or (at your option) any later version.
-- 
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Lesser Public License for more details.
-- 
-- You should have received a copy of the GNU General Lesser Public
-- License along with this program.  If not, see
-- <http://www.gnu.org/licenses/lgpl-3.0.html>.
-- #L%
---
CREATE TABLE CATEGORIES (
    ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFICATION_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TRIGGER CATEGORIES_UPDATE_TR AFTER UPDATE ON CATEGORIES BEGIN
    UPDATE CATEGORIES SET MODIFICATION_DATE = CURRENT_TIMESTAMP WHERE ID = new.ID;
END;
INSERT INTO CATEGORIES (NAME) VALUES ('Category A');
INSERT INTO CATEGORIES (NAME) VALUES ('Category B');
INSERT INTO CATEGORIES (NAME) VALUES ('Category C');
INSERT INTO CATEGORIES (NAME) VALUES ('Category D');

SELECT ID, NAME, CREATION_DATE, MODIFICATION_DATE FROM CATEGORIES;

CREATE TABLE TYPES (
    CODE TEXT(4) NOT NULL PRIMARY KEY,
    PARENT TEXT(4),
    NAME TEXT NOT NULL,
    CONSTRAINT TYPES_PARENT_FK FOREIGN KEY (PARENT) REFERENCES TYPES(CODE) ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO TYPES (CODE, PARENT, NAME) VALUES ('L1', NULL, 'TYPE 1');
INSERT INTO TYPES (CODE, PARENT, NAME) VALUES ('L2', NULL, 'TYPE 2');
INSERT INTO TYPES (CODE, PARENT, NAME) VALUES ('L3', NULL, 'TYPE 3');
INSERT INTO TYPES (CODE, PARENT, NAME) VALUES ('L4', NULL, 'TYPE 4');
INSERT INTO TYPES (CODE, PARENT, NAME) VALUES ('L11', 'L1', 'TYPE 1.1');
INSERT INTO TYPES (CODE, PARENT, NAME) VALUES ('L12', 'L1', 'TYPE 1.2');
INSERT INTO TYPES (CODE, PARENT, NAME) VALUES ('L13', 'L1', 'TYPE 1.3');
INSERT INTO TYPES (CODE, PARENT, NAME) VALUES ('L31', 'L1', 'TYPE 3.1');
INSERT INTO TYPES (CODE, PARENT, NAME) VALUES ('L41', 'L1', 'TYPE 4.1');
INSERT INTO TYPES (CODE, PARENT, NAME) VALUES ('L42', 'L1', 'TYPE 4.2');
INSERT INTO TYPES (CODE, PARENT, NAME) VALUES ('L43', 'L1', 'TYPE 4.3');
INSERT INTO TYPES (CODE, PARENT, NAME) VALUES ('L44', 'L1', 'TYPE 4.4');

SELECT CODE, PARENT, NAME FROM TYPES;

CREATE TABLE ITEMS (
    ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    CODE TEXT(4) NOT NULL,
    NAME TEXT NOT NULL,
    CATEGORY INTEGER NOT NULL,
    "TYPE" TEXT(4),
    CREATION_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFICATION_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ITEMS_CODE_UQ UNIQUE (CODE),
    CONSTRAINT ITEMS_CATEGORY_FK FOREIGN KEY (CATEGORY) REFERENCES CATEGORIES(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT ITEMS_TYPE_FK FOREIGN KEY ("TYPE") REFERENCES TYPES(CODE) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE TRIGGER ITEMS_UPDATE_TR AFTER UPDATE ON ITEMS BEGIN
    UPDATE ITEMS SET MODIFICATION_DATE = CURRENT_TIMESTAMP WHERE ID = new.ID;
END;
INSERT INTO ITEMS (CODE, NAME, CATEGORY, "TYPE") VALUES ('1001', 'Item A1', 1, NULL);
INSERT INTO ITEMS (CODE, NAME, CATEGORY, "TYPE") VALUES ('1002', 'Item A2', 1, 'L12');
INSERT INTO ITEMS (CODE, NAME, CATEGORY, "TYPE") VALUES ('2001', 'Item B1', 2, 'L2');
INSERT INTO ITEMS (CODE, NAME, CATEGORY, "TYPE") VALUES ('2002', 'Item B2', 2, 'L2');
INSERT INTO ITEMS (CODE, NAME, CATEGORY, "TYPE") VALUES ('3001', 'Item C1', 3, NULL);
INSERT INTO ITEMS (CODE, NAME, CATEGORY, "TYPE") VALUES ('4001', 'Item D1', 4, 'L41');
INSERT INTO ITEMS (CODE, NAME, CATEGORY, "TYPE") VALUES ('4002', 'Item D2', 4, 'L42');
INSERT INTO ITEMS (CODE, NAME, CATEGORY, "TYPE") VALUES ('4003', 'Item D3', 4, 'L43');
INSERT INTO ITEMS (CODE, NAME, CATEGORY, "TYPE") VALUES ('4004', 'Item D4', 4, 'L44');

SELECT ID, CODE, NAME, CATEGORY, "TYPE", CREATION_DATE, MODIFICATION_DATE FROM ITEMS;
